# XGBoost in Python

XGBoost is one of the most popular learning algorithm these days. Regardless of the type of prediction task at hand; regression or classification.

## What makes XGBoost so popular?

<b>Speed and performance</b> : Originally written in C++, it is comparatively faster than other ensemble classifiers.

<b>Core algorithm is parallelizable</b> : Because the core XGBoost algorithm is parallelizable it can harness the power of multi-core computers. It is also parallelizable onto GPU’s and across networks of computers making it feasible to train on very large datasets as well.

<b>Consistently outperforms other algorithm methods</b> : It has shown better performance on a variety of benchmark datasets.

<b>Wide variety of tuning parameters</b> : XGBoost internally has parameters for cross-validation, regularization, user-defined objective functions, missing values, tree parameters, scikit-learn compatible API etc.

## Problem Definition

Here we will be using XGBoost to solve a regression problem. The dataset is taken from the UCI Machine Learning Repository and is also present in sklearn's datasets module. It has 14 explanatory variables describing various aspects of residential homes in Boston, the challenge is to predict the median value of owner-occupied homes per $1000s.

In [ ]:
# Import Dataset

from sklearn.datasets import fetch_california_housing
boston = fetch_california_housing()

In [ ]:
# The boston variable itself is a dictionary,
# so you can check for its keys using the .keys() method.

print(boston.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [ ]:
print(boston.data.shape)

(20640, 8)

In [ ]:
print(boston.feature_names)

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']

In [ ]:
print(boston.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. topic:: References

    - Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
      Statistics and Probability Letters, 33 (1997) 291-297

In [ ]:
import pandas as pd

data = pd.DataFrame(boston.data)
data.columns = boston.feature_names

In [ ]:
data.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [ ]:
data['PRICE'] = boston.target

In [ ]:
boston.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [ ]:
data.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,PRICE
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
 8   PRICE       20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

If you plan to use XGBoost on a dataset which has categorical features you may want to consider applying some encoding (like one-hot encoding) to such features before training the model.

Also, if you have some missing values such as NA in the dataset you may or may not do a separate treatment for them, because XGBoost is capable of handling missing values internally.

We will build the model using Trees as base learners (which are the default base learners) using XGBoost's scikit-learn compatible API.

In [ ]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np

In [ ]:
X, y = data.iloc[:,:-1],data.iloc[:,-1]

In [ ]:
X

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [ ]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: PRICE, Length: 20640, dtype: float64

Now you will convert the dataset into an optimized data structure called Dmatrix that XGBoost supports and gives it acclaimed performance and efficiency gains. You will use this later.

In [ ]:
data_dmatrix = xgb.DMatrix(data=X,label=y)

In [ ]:
data_dmatrix.get_label()

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], dtype=float32)

## XGBoost's hyperparameters

learning_rate: step size shrinkage used to prevent overfitting. Range is [0,1]

max_depth: determines how deeply each tree is allowed to grow during any boosting round.

subsample: percentage of samples used per tree. Low value can lead to underfitting.

colsample_bytree: percentage of features used per tree. High value can lead to overfitting.

n_estimators: number of trees you want to build.

objective: determines the loss function to be used like reg:linear for regression problems, reg:logistic for classification problems with only decision, binary:logistic for classification problems with probability.

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123)

In [ ]:
xg_reg = xgb.XGBRegressor(objective ='reg:squarederror', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 10)

In [ ]:
xg_reg.fit(X_train,y_train)

preds = xg_reg.predict(X_test)

In [ ]:
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE: %f" % (rmse))

RMSE: 1.026266

## k-fold Cross Validation using XGBoost


In order to build more robust models, it is common to do a k-fold cross validation where all the entries in the original training dataset are used for both training as well as validation. Also, each entry is used for validation just once. XGBoost supports k-fold cross validation via the cv() method.

In [ ]:
params = {"objective":"reg:squarederror",'colsample_bytree': 0.3,'learning_rate': 0.1,
                'max_depth': 5, 'alpha': 10}

cv_results = xgb.cv(dtrain=data_dmatrix, params=params, nfold=3,
                    num_boost_round=50,early_stopping_rounds=10,
                    metrics="rmse", as_pandas=True, seed=123)

In [ ]:
# cv_results contains train and test RMSE metrics for each boosting round.
cv_results.head(51)

    train-rmse-mean  train-rmse-std  test-rmse-mean  test-rmse-std
0          1.821499        0.007852        1.821568       0.016809
1          1.696677        0.010869        1.698385       0.029091
2          1.569698        0.014009        1.571751       0.035465
3          1.465133        0.019988        1.468298       0.039061
4          1.380916        0.030291        1.385067       0.049235
5          1.300314        0.031372        1.304501       0.052176
6          1.221882        0.026839        1.226668       0.044177
7          1.156018        0.020585        1.160406       0.035470
8          1.094199        0.017770        1.099508       0.035548
9          1.045339        0.027343        1.051521       0.045473
10         1.005812        0.028004        1.012308       0.046192
11         0.967694        0.031773        0.974758       0.049799
12         0.940511        0.033658        0.947941       0.051195
13         0.902066        0.030555        0.909651       0.046861
14         0.865528        0.028381        0.873743       0.043951
15         0.839474        0.025683        0.848454       0.041776
16         0.816656        0.016951        0.826309       0.032357
17         0.794641        0.022266        0.804871       0.036746
18         0.770556        0.019311        0.781710       0.034231
19         0.758116        0.021204        0.769497       0.036077
20         0.745059        0.015973        0.756716       0.030588
21         0.732879        0.013878        0.745345       0.028240
22         0.715187        0.008782        0.727797       0.022627
23         0.700894        0.007891        0.714228       0.021055
24         0.688231        0.003780        0.701716       0.017622
25         0.680633        0.002245        0.694343       0.014855
26         0.671209        0.005739        0.685208       0.017318
27         0.662561        0.004251        0.677115       0.015359
28         0.654712        0.001645        0.670229       0.013815
29         0.647305        0.001859        0.663065       0.011705
30         0.642620        0.003080        0.658739       0.010056
31         0.636879        0.004516        0.653763       0.009662
32         0.631527        0.003849        0.648635       0.009301
33         0.623931        0.001679        0.641461       0.011211
34         0.619725        0.002018        0.637495       0.010671
35         0.616869        0.003485        0.634808       0.009285
36         0.613196        0.003268        0.631413       0.010070
37         0.609081        0.003541        0.627643       0.010245
38         0.603938        0.005179        0.622825       0.010482
39         0.598352        0.007414        0.617414       0.011358
40         0.592983        0.004312        0.612604       0.010257
41         0.588990        0.003474        0.609332       0.009789
42         0.586865        0.003519        0.607411       0.009610
43         0.584849        0.003951        0.605494       0.010792
44         0.582309        0.004410        0.603454       0.009742
45         0.580603        0.004810        0.601974       0.008801
46         0.576604        0.005149        0.598034       0.012426
47         0.574196        0.003654        0.596241       0.011674
48         0.572147        0.003941        0.594198       0.012383
49         0.570792        0.004006        0.593201       0.011952